<?php

return [
    [
        'nome' => 'Castelo Branco',
        'codigo' => '0502',
        'freguesias' => [
            ['codigo' => '050201', 'nome' => 'Alcains'],
            ['codigo' => '050202', 'nome' => 'Almaceda'],
            ['codigo' => '050203', 'nome' => 'Benquerenças'],
            ['codigo' => '050206', 'nome' => 'Cebolais de Cima e Retaxo'],
            ['codigo' => '050205', 'nome' => 'Castelo Branco'],
            ['codigo' => '050207', 'nome' => 'Escalos de Baixo e Mata'],
            ['codigo' => '050208', 'nome' => 'Escalos de Cima e Lousa'],
            ['codigo' => '050209', 'nome' => 'Freixial do Campo e Juncal do Campo'],
            ['codigo' => '050211', 'nome' => 'Lardosa'],
            ['codigo' => '050212', 'nome' => 'Louriçal do Campo'],
            ['codigo' => '050214', 'nome' => 'Malpica do Tejo'],
            ['codigo' => '050216', 'nome' => 'Monforte da Beira'],
            ['codigo' => '050217', 'nome' => 'Ninho do Açor e Sobral do Campo'],
            ['codigo' => '050218', 'nome' => 'Póvoa de Rio de Moinhos e Cafede'],
            ['codigo' => '050220', 'nome' => 'Salgueiro do Campo'],
            ['codigo' => '050221', 'nome' => 'Santo André das Tojeiras'],
            ['codigo' => '050222', 'nome' => 'São Vicente da Beira'],
            ['codigo' => '050223', 'nome' => 'Sarzedas'],
            ['codigo' => '050225', 'nome' => 'Tinalhas'],
        ],
    ],
    [
        'nome' => 'Idanha-a-Nova',
        'codigo' => '0505',
        'freguesias' => [
            ['codigo' => '050503', 'nome' => 'Idanha-a-Nova'],
            ['codigo' => '050502', 'nome' => 'Aldeia de Santa Margarida'],
            ['codigo' => '050505', 'nome' => 'Ladoeiro'],
            ['codigo' => '050506', 'nome' => 'Medelim'],
            ['codigo' => '050508', 'nome' => 'Monsanto e Idanha-a-Velha'],
            ['codigo' => '050509', 'nome' => 'Oledo'],
            ['codigo' => '050510', 'nome' => 'Penha Garcia'],
            ['codigo' => '050511', 'nome' => 'Proença-a-Velha'],
            ['codigo' => '050512', 'nome' => 'Rosmaninhal'],
            ['codigo' => '050514', 'nome' => 'São Miguel de Acha'],
            ['codigo' => '050515', 'nome' => 'Segura'],
            ['codigo' => '050516', 'nome' => 'Toulões'],
            ['codigo' => '050517', 'nome' => 'Zebreira e Benquerença'],
        ],
    ],
    [
        'nome' => 'Oleiros',
        'codigo' => '0506',
        'freguesias' => [
            ['codigo' => '050601', 'nome' => 'Álvaro'],
            ['codigo' => '050603', 'nome' => 'Cambas'],
            ['codigo' => '050604', 'nome' => 'Estreito'],
            ['codigo' => '050605', 'nome' => 'Isna'],
            ['codigo' => '050606', 'nome' => 'Madeirã'],
            ['codigo' => '050607', 'nome' => 'Mosteiro'],
            ['codigo' => '050608', 'nome' => 'Oleiros'],
            ['codigo' => '050609', 'nome' => 'Orvalho'],
            ['codigo' => '050610', 'nome' => 'Sarnadas de São Simão'],
            ['codigo' => '050611', 'nome' => 'Sobral'],
        ],
    ],
    [
        'nome' => 'Penamacor',
        'codigo' => '0507',
        'freguesias' => [
            ['codigo' => '050704', 'nome' => 'Aranhas'],
            ['codigo' => '050706', 'nome' => 'Benquerença'],
            ['codigo' => '050707', 'nome' => 'Meimão'],
            ['codigo' => '050708', 'nome' => 'Meimoa'],
            ['codigo' => '050710', 'nome' => 'Penamacor'],
            ['codigo' => '050711', 'nome' => 'Salvador'],
            ['codigo' => '050702', 'nome' => 'Aldeia do Bispo, Águas e Aldeia de João Pires'],
            ['codigo' => '050709', 'nome' => 'Pedrógão de São Pedro e Bemposta'],
            ['codigo' => '050712', 'nome' => 'Vale da Senhora da Póvoa'],
        ],
    ],
    [
        'nome' => 'Proença-a-Nova',
        'codigo' => '0508',
        'freguesias' => [
            ['codigo' => '050802', 'nome' => 'Montes da Senhora'],
            ['codigo' => '050804', 'nome' => 'Proença-a-Nova e Peral'],
            ['codigo' => '050805', 'nome' => 'São Pedro do Esteval'],
            ['codigo' => '050806', 'nome' => 'Sobreira Formosa e Alvito da Beira'],
        ],
    ],
    [
        'nome' => 'Sertã',
        'codigo' => '0509',
        'freguesias' => [
            ['codigo' => '050901', 'nome' => 'Cabeçudo'],
            ['codigo' => '050902', 'nome' => 'Carvalhal'],
            ['codigo' => '050903', 'nome' => 'Castelo'],
            ['codigo' => '050911', 'nome' => 'Pedrógão Pequeno'],
            ['codigo' => '050912', 'nome' => 'Sertã'],
            ['codigo' => '050913', 'nome' => 'Troviscal'],
            ['codigo' => '050914', 'nome' => 'Várzea dos Cavaleiros'],
            ['codigo' => '050904', 'nome' => 'Cernache do Bonjardim, Nesperal e Palhais'],
            ['codigo' => '050905', 'nome' => 'Cumeada e Marmeleiro'],
            ['codigo' => '050906', 'nome' => 'Ermida e Figueiredo'],
        ],
    ],
    [
        'nome' => 'Vila de Rei',
        'codigo' => '0510',
        'freguesias' => [
            ['codigo' => '051001', 'nome' => 'Fundada'],
            ['codigo' => '051002', 'nome' => 'São João do Peso'],
            ['codigo' => '051003', 'nome' => 'Vila de Rei'],
        ],
    ],
    [
        'nome' => 'Vila Velha de Ródão',
        'codigo' => '0511',
        'freguesias' => [
            ['codigo' => '051101', 'nome' => 'Fratel'],
            ['codigo' => '051102', 'nome' => 'Perais'],
            ['codigo' => '051103', 'nome' => 'Sarnadas de Ródão'],
            ['codigo' => '051104', 'nome' => 'Vila Velha de Ródão'],
        ],
    ],
];
