<?php

// Lista de nacionalidades

return [
    'Afegã',
    'Sul-Africana',
    'Albanesa',
    'Alemã',
    'Angolana',
    'Saudita',
    'Argelina',
    'Argentina',
    'Arménia',
    'Australiana',
    'Austríaca',
    'Azerbaijana',
    'Bangladexe',
    'Belga',
    'Boliviana',
    'Bósnia',
    'Brasileira',
    'Cabo-Verdiana',
    'Camaronesa',
    'Canadiana',
    'Chilena',
    'Chinesa',
    'Cipriota',
    'Colombiana',
    'Coreana (Norte)',
    'Coreana (Sul)',
    'Costa-Marfinense',
    'Croata',
    'Cubana',
    'Dinamarquesa',
    'Egípcia',
    'Equatoriana',
    'Eslovaca',
    'Eslovena',
    'Espanhola',
    'Americana',
    'Estoniana',
    'Etíope',
    'Filipina',
    'Finlandesa',
    'Francesa',
    'Ganesa',
    'Grega',
    'Guineense (Bissau)',
    'Guineense (Equatorial)',
    'Holandesa',
    'Húngara',
    'Indiana',
    'Indonésia',
    'Inglesa (Britânica)',
    'Iraniana',
    'Iraquiana',
    'Irlandesa',
    'Italiana',
    'Japonesa',
    'Letã',
    'Lituana',
    'Luxemburguesa',
    'Malaia',
    'Marroquina',
    'Mexicana',
    'Moçambicana',
    'Moldava',
    'Nepalesa',
    'Nigeriana',
    'Norueguesa',
    'Paquistanesa',
    'Paraguaia',
    'Peruana',
    'Polaca',
    'Portuguesa',
    'Queniana',
    'Checa',
    'Romena',
    'Russa',
    'Santomense',
    'Senegalesa',
    'Sérvia',
    'Síria',
    'Sueca',
    'Suíça',
    'Tailandesa',
    'Timorense',
    'Turca',
    'Ucraniana',
    'Uruguaia',
    'Venezuelana',
    'Vietnamita',
    'Outra',
];